### PR TITLE
Merge develop into master - the right way!

### PR DESCRIPTION
**Pull request by tjhorner**

### CODE REVIEW

**Comment by tjhorner** [comment]
(just force push from cli lol)

**Comment by rodrigoargumedo** [comment]
I just think that we need to get hands off the master branch. Out of ordinary, merging develop branch would be a disaster unless Tyler is confident enough to merge it.
Rodrigo Argumedo
Sent from iCloud via Web

On Feb 18, 2015, at 11:10 PM, TJ Horner <notifications@github.com> wrote:

Reopened #7.

**Comment by tjhorner** [comment]
He had no idea the code was being pushed to develop:

> it's just on develop for some reason

**Comment by rodrigoargumedo** [comment]
I know the source code from the master branch is so outdated but I may/may not agree to merge this pull request depending on @tylermenezes's actions. In short, yeah, what would happen if he created another branch containing the master branch code and merge it afterwards?

**Comment by tylermenezes** [comment]
@rodrigoargumedo all of the active development is actually happening on the develop branch right now, and master is just a super old version of the site that's still in master because -- if I remember correctly -- we had to get the site launched in less than an hour and didn't want to deal with branch merging.

**Comment by tylermenezes** [comment]
I think the right way is probably to delete everything and rebase the code from develop in.

**Comment by tjhorner** [comment]
This is one of the very rare occasions where the right way is to delete everything because everything is so different that git would commit suicide if you tried to merge.

**Comment by rodrigoargumedo** [comment]
@tjhorner Yeah, this case is very rare but rebasing the branch would be sort of a pain because the repository has very old code and `rm -rf`off the entire master branch would be a mess. At this point, no changes will be made in the master branch. Considering closing this pull request.

**Comment by tjhorner** [comment]
@tylermenezes should I try to merge develop into master from cli?

**Comment by tjhorner** [comment]
Done.

**Comment by tjhorner** [comment]
Restored `develop` branch for historical purposes. The history does not come through.

**Pull request merged**
